apiVersion: v1
kind: ConfigMap
metadata:
  name: "rabbitmq-config"
data:
  # [rabbitmq_management,rabbitmq_peer_discovery_k8s].
  enabled_plugins: |
    [rabbitmq_management].
  rabbitmq.conf: |
    ## Clustering
    management.load_definitions = /etc/rabbitmq/rabbitmq_definitions.json
    #cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    #cluster_formation.k8s.host = kubernetes.default.svc
    ## cluster_formation.k8s.port = 8443
    #cluster_formation.k8s.address_type = ip
    #cluster_formation.node_cleanup.interval = 10
    #cluster_formation.node_cleanup.only_log_warning = false
    #cluster_partition_handling = autoheal
    ## queue master locator
    queue_master_locator=min-masters
    ## enable guest user
    loopback_users.guest = false
  rabbitmq_definitions.json: |
    {
      "users":[{"name": "awx", "password": "awxpass", "tags": ""}],
      "permissions":[
        {"user":"awx","vhost":"awx","configure":".*","write":".*","read":".*"}
      ],
      "vhosts":[{"name":"awx"}],
      "policies":[
          {"vhost":"awx","name":"ha-all","pattern":".*","definition":{"ha-mode":"all","ha-sync-mode":"automatic"}}
      ]
    }

