apiVersion: v1
kind: Secret
metadata:
  name: "awx-secrets"
type: Opaque
data:
  admin_password: cGFzc3dvcmQ=
  credentials_py: |
    aW1wb3J0IG9zCgpEQVRBQkFTRVMgPSB7CiAgICAnZGVmYXVsdCc6IHsKICAg
    ICAgICAnQVRPTUlDX1JFUVVFU1RTJzogVHJ1ZSwKICAgICAgICAnRU5HSU5F
    JzogJ2F3eC5tYWluLmRiLnByb2ZpbGVkX3BnJywKICAgICAgICAnTkFNRSc6
    ICJhd3giLAogICAgICAgICdVU0VSJzogImF3eCIsCiAgICAgICAgJ1BBU1NX
    T1JEJzogImF3eHBhc3MiLAogICAgICAgICdIT1NUJzogb3MuZW52aXJvbi5n
    ZXQoIlBPU1RHUkVTUUxfSE9TVCIpLAogICAgICAgICdQT1JUJzogIjU0MzIi
    LAogICAgfQp9CkJST0tFUl9VUkwgPSAnYW1xcDovL3t9Ont9QHt9Ont9L3t9
    Jy5mb3JtYXQoCiAgICAiYXd4IiwKICAgICJhd3hwYXNzIiwKICAgIG9zLmVu
    dmlyb24uZ2V0KCJSQUJCSVRNUV9IT1NUIiksCiAgICAiNTY3MiIsCiAgICAi
    YXd4IikKQ0hBTk5FTF9MQVlFUlMgPSB7CiAgICAnZGVmYXVsdCc6IHsnQkFD
    S0VORCc6ICdhc2dpX2FtcXAuQU1RUENoYW5uZWxMYXllcicsCiAgICAgICAg
    ICAgICAgICAnUk9VVElORyc6ICdhd3gubWFpbi5yb3V0aW5nLmNoYW5uZWxf
    cm91dGluZycsCiAgICAgICAgICAgICAgICAnQ09ORklHJzogeyd1cmwnOiBC
    Uk9LRVJfVVJMfX0KfQo=
  environment_sh: |
    REFUQUJBU0VfVVNFUj1hd3gKREFUQUJBU0VfTkFNRT1hd3gKREFUQUJBU0Vf
    UE9SVD01NDMyCkRBVEFCQVNFX1BBU1NXT1JEPWF3eHBhc3MKQVdYX0FETUlO
    X1VTRVI9YWRtaW4KQVdYX0FETUlOX1BBU1NXT1JEPXBhc3N3b3JkCg==
  pg_password: YXd4cGFzcw==
  rabbitmq_erlang_cookie: Y29va2llbW9uc3Rlcg==
  rabbitmq_password: YXd4cGFzcw==
  secret_key: YXd4c2VjcmV0

#
# DECODED DATA
#
# pg_password: awxpass
# rabbitmq_erlang_cookie: cookiemonster
# rabbitmq_password: awxpass
# secret_key: awxsecret
#
#
# credentials_py:
# ----
# import os
# 
# DATABASES = {
#     'default': {
#         'ATOMIC_REQUESTS': True,
#         'ENGINE': 'awx.main.db.profiled_pg',
#         'NAME': "awx",
#         'USER': "awx",
#         'PASSWORD': "awxpass",
#         'HOST': os.environ.get("POSTGRESQL_HOST"),
#         'PORT': "5432",
#     }
# }
# BROKER_URL = 'amqp://{}:{}@{}:{}/{}'.format(
#     "awx",
#     "awxpass",
#     os.environ.get("RABBITMQ_HOST"),
#     "5672",
#     "awx")
# CHANNEL_LAYERS = {
#     'default': {'BACKEND': 'asgi_amqp.AMQPChannelLayer',
#                 'ROUTING': 'awx.main.routing.channel_routing',
#                 'CONFIG': {'url': BROKER_URL}}
# }
# 
#
# environment_sh:
# ----
# DATABASE_USER=awx
# DATABASE_NAME=awx
# DATABASE_PORT=5432
# DATABASE_PASSWORD=awxpass
# AWX_ADMIN_USER=admin
# AWX_ADMIN_PASSWORD=password
